#############################################
#### Environment variable  for scripts ######
#############################################

## Ipaddress variable
#  Assigning IP for controller node
CTL_MGNT_IP=10.10.10.10
CTL_EXT_IP=192.168.2.10
CTL_DATA_IP=10.10.20.10
CTL_MGNT_IF=ens3
CTL_EXT_IF=ens4
CTL_DATA_IF=ens5



# Assigning IP for Compute1 host
COM1_MGNT_IP=10.10.10.20
COM1_EXT_IP=192.168.2.20
COM1_DATA_IP=10.10.20.20
COM1_MGNT_IF=ens3
COM1_EXT_IF=ens4
COM1_DATA_IF=ens5

# Assigning IP for Compute1 host
CINDER_MGNT_IP=10.10.10.30
CINDER_EXT_IP=192.168.2.30
CINDER_DATA_IP=10.10.20.30
CINDER_MGNT_IF=ens3
CINDER_EXT_IF=ens4
CINDER_DATA_IF=ens5

# Gateway for EXT network
GATEWAY_IP_EXT=192.168.2.1
NETMASK_ADD_EXT=255.255.255.0



# Gateway for MGNT network
GATEWAY_IP_MGNT=10.10.10.1
SUBNETMASK_MGNT=10.10.10.0/24
NETMASK_ADD_MGNT=255.255.255.0


# Gateway for DATA network
GATEWAY_IP_DATA=10.10.20.1
NETMASK_ADD_DATA=255.255.255.0


## Hostname variable
HOST_CTL=controller
HOST_COM1=compute1
HOST_CINDER=cinder



#### Floating IP pool

PROVIDER_NETWORK_GATEWAY="$GATEWAY_IP_EXT"
START_IP_ADDRESS=192.168.2.150
END_IP_ADDRESS=192.168.2.200
DNS_RESOLVER=8.8.8.8
PROVIDER_NETWORK_CIDR=192.168.2.0/24


## Password variable
# Set password
DEFAULT_PASS=welcome123


RABBIT_PASS="$DEFAULT_PASS"
MYSQL_PASS="$DEFAULT_PASS"
TOKEN_PASS="$DEFAULT_PASS"
ADMIN_PASS="$DEFAULT_PASS"
DEMO_PASS="$DEFAULT_PASS"
SERVICE_PASSWORD="$DEFAULT_PASS"
METADATA_SECRET="$DEFAULT_PASS"

SERVICE_TENANT_NAME="service"
ADMIN_TENANT_NAME="admin"
DEMO_TENANT_NAME="demo"
INVIS_TENANT_NAME="invisible_to_admin"
ADMIN_USER_NAME="admin"
DEMO_USER_NAME="demo"

# Password variable for OPS service
KEYSTONE_PASS="$DEFAULT_PASS"
GLANCE_PASS="$DEFAULT_PASS"
NOVA_PASS="$DEFAULT_PASS"
NEUTRON_PASS="$DEFAULT_PASS"
CINDER_PASS="$DEFAULT_PASS"
SWIFT_PASS="$DEFAULT_PASS"
HEAT_PASS="$DEFAULT_PASS"
CEILOMETER_PASS="$DEFAULT_PASS"
PLACEMENT_PASS="$DEFAULT_PASS"

# Environment variable for DB
KEYSTONE_DBPASS="$DEFAULT_PASS"
GLANCE_DBPASS="$DEFAULT_PASS"
NOVA_DBPASS="$DEFAULT_PASS"
NOVA_API_DBPASS="$DEFAULT_PASS"
NEUTRON_DBPASS="$DEFAULT_PASS"
CINDER_DBPASS="$DEFAULT_PASS"
HEAT_DBPASS="$DEFAULT_PASS"
CEILOMETER_DBPASS="$DEFAULT_PASS"
SAHARA_PASS="$DEFAULT_PASS"

# User declaration in Keystone
ADMIN_ROLE_NAME="admin"
MEMBER_ROLE_NAME="user"
KEYSTONEADMIN_ROLE_NAME="KeystoneAdmin"
KEYSTONESERVICE_ROLE_NAME="KeystoneServiceAdmin"

# OS PASS ROOT
